name: Docs Bug 🐞 report
description: Report mistakes and/or bugs in Jitsi Docs.
title: "[Docs Bug 🐞 report]: "
labels: ["🐞 docs bug"]
  
body:
  - type: markdown
    attributes:
      value: |
        Thank you for reporting mistakes and/or bugs 🐞 in Jitsi Docs 📑. We appreciate your contribution! 🙂
  
  - type: textarea
    id: describe-bug
    attributes:
      label: Describe the bug you found in Jitsi Docs.
      description: Is there a bug in one of our code snippets? Did we explain a concept incorrectly? Please share a clear and concise description of what the bug or mistake is.
      placeholder: "I would like to file an Jitsi Docs Bug 🐞 report about..."
    validations:
      required: true
      
  - type: textarea
    id: reproduce-bug
    attributes:
      label: Attach any resources that can help us understand the issue.
      description: Send us screenshots, direct quotes of the text that has issues, a link to the GitHub repository with project that has issues, etc. Help us reproduce this Docs issue.
      placeholder: "Please find attached a screenshot of the text with issues..."
    validations:
      required: true

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our Code of Conduct
      options:
        - label: "please make sure you check https://community.jitsi.org"
          required: true

  - type: dropdown
    attributes:
      label: Are you willing to work on this issue ?
      description: This is absolutely not required, but we are happy to guide you in the contribution process.
      options:
        - "Yes I am willing to submit a PR!"
        - "No, someone else can work on it" 
