name: 💡 Feature Request
description: Suggest a new idea/feature
title: "[FEATURE] <description>"
labels: ["enhancement"]

body:
  - type: textarea
    id: need_improvement
    attributes:
      label: Why do we need this improvement?
    validations:
      required: true

  - type: textarea
    id: change
    attributes:
      label: How will this change help?
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: Please add screenshots if applicable
    validations:
      required: false


  - type: textarea
    id: implemented
    attributes:
      label: How could it be implemented/designed?
    validations:
      required: true
  
  - type: dropdown
    id: breakingchange
    attributes:
      label: "🚧 Breaking changes"
      description: "Will this be a breaking change?"
      options:
        - "Yes"
        - "No"
    validations:
      required: true

  - type: checkboxes
    id: no-duplicate-issues
    attributes:
      label: "👀 Have you checked for similar open issues?"
      options:
        - label: "I checked and didn't find a similar issue"
          required: true

  - type: checkboxes
    id: check-Community-Forum
    attributes:
      label: "🏢 Have you checked the Community Forum?"
      options:
        - label: "please make sure you check https://community.jitsi.org"
          required: true
