/** Event triggered by NoAudioSignalDetector when the local audio device associated with a JitsiConference goes silent
 * for a period of time, meaning that the device is either broken or hardware/software muted.
 * @event
 * @type {Object} - empty
 */
export const NO_AUDIO_INPUT = 'no_audio_input_detected';

/** Event triggered by {@link NoAudioSignalDetector} when the local audio device associated with a JitsiConference
 * starts receiving audio levels with the value of 0 meaning no audio is being captured on that device, or when
 * it starts receiving audio levels !== 0 after being in a state of no audio.
 * @event
 * @type {boolean} - true when the current conference audio track has audio input false otherwise.
 */
export const AUDIO_INPUT_STATE_CHANGE = 'audio_input_state_changed';

/**
 * Event generated by {@link TrackVADEmitter} when PCM sample VAD score is available.
 *
 * @event
 * @type {Object}
 * @property {Date}   timestamp - Exact time at which processed PCM sample was generated.
 * @property {number} score - VAD score on a scale from 0 to 1 (i.e. 0.7)
 * @property {string} deviceId - Device id of the associated track.
 */
export const VAD_SCORE_PUBLISHED = 'detection.vad_score_published';

/**
 *  Event generated by {@link VADTalkMutedDetection} when a user is talking while the mic is muted.
 *
 *  @event
 *  @type {Object}
 */
export const VAD_TALK_WHILE_MUTED = 'detection.vad_talk_while_muted';
